<?php
/**
*
Implementation of hook_init()
*
*/



function custom_maxhealthlab_init() {
	global $user;
     if($_GET['q']== "node/70") { 
        if(!in_array("Wellness Affiliate",$user->roles)){
            drupal_goto("<front>");
        } 
     }       
}
/**
 * Implements hook_perm().
 */
function custom_maxhealthlab_perm() {
  return array(
    'access affiliate user listing',
  );
}
/**
 * Implements hook_menu().
 */
function custom_maxhealthlab_menu() {
	$items['admin/user/wa_user'] = array(                                  
		'title'=> t('New WA Request'),
		'page callback'=> 'custom_maxhealthlab_user_listing',
		'type' =>MENU_NORMAL_ITEM,
		'access callback' => 'user_access',
		'access arguments' => array('access affiliate user listing'),
	);
	$items['admin/user/accept/%']=array(
		'title' => 'Approve affiliate user',
		'page callback'=> 'approve_affiliate_user_account',
		'page arguments'=>array(3),
		'access callback' => 'user_access',
		'access arguments' => array('access affiliate user listing'),
		'type' => MENU_CALLBACK,
        );
	
	return $items;
}
function custom_maxhealthlab_user_listing() {
  global $base_url;
   $header = array(
    array('data' => t('Uid'), 'field' => 'u.uid', 'sort' => 'desc'),
    array('data' => t('Username'), 'field' => 'u.name'),
    array('data' => t('Email Address'), 'field' => 'u.mail'),
    array('data' => t('')),
    array('data' => t('')),
    array('data' => t('')),
   ); 
  $rows = array();
  $limit = 2;
  $cntuser = "SELECT COUNT(*) as cnt FROM {users} WHERE uid != 0 and mail in 
                (SELECT data FROM webform_submitted_data WHERE cid = 6 AND nid = 60)";
  
  $resultUser= pager_query("SELECT uid,name,mail FROM users u WHERE uid != 0 and mail in 
                (SELECT data FROM webform_submitted_data WHERE cid = '6' AND nid = '60')".
		tablesort_sql($header), $limit, 0,$cntuser);
  while ($waUser = db_fetch_object($resultUser)) {
          $view_user_link = '<a href="'.$base_url.'/user/'.$waUser->uid.'" class ="" > View </a>';
	  $accept_user_link = '<a href="'.$base_url.'/admin/user/accept/'.$waUser->uid.'" class ="" > Accept </a>';
	  $delete_user_link = l(t('Delete'),'user/'.$waUser->uid.'/delete',array('query' => drupal_get_destination()));
	  $rows[] = array(
	    array('data' => $waUser->uid ,'align' => 'left'),
	    array('data' => $waUser->name,'nowrap' => 'nowrap'),
	    array('data' => $waUser->mail, 'nowrap' => 'nowrap'),
	    array('data' => $view_user_link),
	    array('data' => $accept_user_link),
	    array('data' => $delete_user_link),
	  );
  }
  if (empty($rows)) {
    $rows[] = array(array('data' => t('No orders available.'), 'colspan' => 5));
  }

  return theme('table', $header, $rows, array('class' => 'wa-user-listing'))
       . theme('pager', NULL, 20, 0);
}
function custom_maxhealthlab_form_alter(&$form, $form_state, $form_id) {
	if ($form_id == 'uc_cart_view_form') {
	     	//Here I just remove the title of the image column
		$form['items']['#columns']['image']['cell'] = '';

		//Now I am moving around the columns by adjusting the weight
		$form['items']['#columns']['image']['weight'] = 0;
		$form['items']['#columns']['desc']['weight'] = 1;
		$form['items']['#columns']['qty']['weight'] = 2;
		$form['items']['#columns']['total']['weight'] = 3;
		$form['items']['#columns']['remove']['weight'] = 4;
	}
	if($form_id == "uc_cart_checkout_form") {
		//print_r($form['panes']['customer']);
	/*	$form['panes']['customer']['password'] = array(
			'#type' => 'password',
			'#title' => 'Password',
			'#value' => '',
			'#size' => '32',
                        '#maxlength' => '64',
			'#required' => TRUE,
		);
		$form['panes']['customer']['password'] = array(
			'#type' => 'password_confirm',
			'#size' => '32',
                        '#maxlength' => '64',
			'#required' => TRUE,
		);

            */
	}
	if($form_id == "webform_client_form_60") {
	      	if(arg(2) != "submission" && arg(4) != "edit") {
		  $form['#submit'][] = 'affiliate_user_register';
		}
		
	} 

	if($form_id == "user_login_block") {
		//print_r($form);
		$form['name']['#title'] = t("Username or e-mail address");
		$form['name']['#description'] = t("You may login with either your assigned username or your e-mail address.");
		$form['pass']['#description'] = t("The password field is case sensitive.");
		$form['links']['#weight'] = 1;
                $form['submit']['#weight'] = 2;
		$items[] = l(t('Request new password'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'))));
                $form['links'] = array('#value' => theme('item_list', $items));

	}
}

function affiliate_user_register($form,$form_state) {
    // New user creation
    $name = $form['#post']['submitted']['first_name']."_".$form['#post']['submitted']['last_name'];
    $mail = $form['#post']['submitted']['email_address'];
    $pass = "123";
    $account = new stdClass();
    $account->is_new = true;
    $newUserData = array(
    'name' => $mail,
    'pass' => $pass, // note: do not md5 the password
    'mail' => $mail,
    'status' => 0,
    'timezone' => 'Europe/Paris',
    'init' => $mail,
    'roles' => array(
    '4' => 'Affiliate user', 
     ),
    );

    $new_user = user_save($account, $newUserData);
    if($new_user) {
      return Success;
    }
    else {
      return error; 
    } 
}

/**
 * Implementation of hook_mail().
 */

function custom_maxhealthlab_mail($key, &$message, $params) {
    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';   
    $options['language'] = $message['language'];
    $variables = user_mail_tokens($params['account'], $language);
    switch($key) {
      case 'mhl_one_time_login_mail':
        $langcode = $message['language']->language;
        $message['subject'] .= t('Account details for !username at !site', $variables, $langcode);
        $message['body'] = t("!username,\n\nThank you for registering at !site. You may now log in to !login_uri using the following username and password:\n\nusername: !username\npassword: !password\n\nYou may also log in by clicking on this link or copying and pasting it in your browser:\n\n!login_url\n\nThis is a one-time login, so it can be used only once.\n\nAfter logging in, you will be redirected to !edit_uri so you can change your password.\n\n\n--  !site team", $variables, $langcode);
        break;     
    }
 //print_r($message);
}

/*** 
* Menu callback function to show listing of all user who have submitted web inquiry form.
*
*/

function approve_affiliate_user_account($uid) {
     
    $rs = db_query("Update {users} set status = 1 where uid =%d",$uid); 
    $from = 'shubhangi.bandal@clariontechnologies.co.in';
    $account = user_load($uid); 
    $params['account'] = $account;
    $sql = "SELECT uid,name,mail FROM users u WHERE u.uid =".$uid;
    $rsUser = db_query($sql);
    while($rowUser = db_fetch_object($rsUser)) {
	$to = $rowUser->mail;
	$mail_to = $to;
	if (drupal_mail('custom_maxhealthlab', 'mhl_one_time_login_mail', $mail_to, language_default(), $params, $from, TRUE)) {
        	drupal_set_message('An email has been sent to ' . $mail_to);       
        } else {
 		drupal_set_message('There was an error sending your email');
        } 

     }
     drupal_goto("admin/user/wa_user");
}

/**
* Implementation of hook_user().
*/

function custom_maxhealthlab_user($op, &$edit, &$account, $category = NULL) {
   if($op == "insert") {
         $edit['first_time_login'] = 1;
   }
   if ($op == 'login') {
    /* print_r($account);
    print_r($_REQUEST['destination']);
    print_r($_GET['destination']);
    die(); */
    $data = unserialize($account->data);
            if(in_array("Retail Customer",$account->roles)){
		 drupal_goto("online-store");
	      }
	      else if(in_array("Wellness Affiliate",$account->roles)){
	         if($account->access == 0){
                         drupal_set_message("You have just used your one-time login link. It is no longer necessary to use this link to login. Please change your password.");
			 drupal_goto("user/".$account->uid."/edit");
		      } else {
			 drupal_goto('wa-landing');
		      }
	      }
	      else {
		 drupal_goto('user');
	      } 
	   }
}
/* function custom_maxhealthlab_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {

	 switch ($op) {
	 case 'presave':
	 break;
	 case 'insert':
	 case 'update':
		print_r($node);
		die();
		break;
	 }
} */